# Bienvenido a Jekyll!
#
# Este archivo de configuración está destinado a configuraciones que afectan todo tu blog,
# valores que deberías configurar una vez y editar raramente después de eso. Si te encuentras
# editando este archivo con frecuencia, considera usar los archivos de datos de Jekyll para la
# información que necesitas actualizar con frecuencia.

# Configuración del sitio
locale: "es-ES"
title: Ojitomo Web
email:
description: "Pagina Web de ojitomo donde publica reseñas, tutoriales, guías o cualquier otra cosa de interés propio."
logo: "/assets/images/logo.png"
comments:
  provider: "disqus"
  disqus:
    shortname: "ojitomo"
    enabled: true
twitter_username: username
github_username: username
minimal_mistakes_skin: "sunrise"
search: true

# Configuración de la construcción
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Salida
permalink: /:collection/:title/
paginate: 5
paginate_path: /page:num/

# Archivos a incluir
include:
  - _includes
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-archives

# Información del autor
author:
  name   : "Ojitomo78"
  avatar : "/assets/images/bio-photo.png"
  bio    : "Solo salto entre mundos"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/Ojitomo78"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/ojitomo78/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ojitomo78"

# Enlace del pie de página
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/Ojitomo78"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ojitomo78"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/ojitomo78/"
    - label: "Post por Año"
      icon: "fa-solid fa-calendar-days"
      url: "/posts/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Archivos de categorías y etiquetas
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
